""" Code to add link in PyPSA,
NOTE: it requires an existing pypsa network
and the values generated by the pre_processing script"""

n.add('Bus','CO2s_perennials',carrier = 'CO2', unit = 't')

n.add('Link',
      'perennials_GBR',
      bus0="CO2_atm",
      bus1="CO2s_perennials",
      bus2="el",
      bus3 ="biogas",
      efficiency=1,
      efficiency2 = -eff_el,
      efficiency3 = eff_biogas,
      p_nom_extendable=True,
      p_max_pu = df_gbr["harvest"],
      capital_cost=tech_costs.at['Perennials_GBR', "fixed"],
      marginal_cost=tech_costs.at['Perennials_GBR', "VOM"])

n.add('Store',
      'CO2s_perennials',
      bus= 'CO2s_perennials',
      e_nom_extendable= False,
      e_nom_max = CO2s_potential_perennials,
      e_cyclic = False)


